//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.VSTO.CCForm {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCForm.CCFormAPISoap")]
    public interface CCFormAPISoap {
        
        // CODEGEN: 参数“bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BP.VSTO.CCForm.GenerExcelFileResponse GenerExcelFile(BP.VSTO.CCForm.GenerExcelFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerDBForVSTOExcelFrmModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GenerDBForVSTOExcelFrmModel(string userNo, string sid, string frmID, string pkValue, string atParas);
        
        // CODEGEN: 参数“byt”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BP.VSTO.CCForm.SaveExcelFileResponse SaveExcelFile(BP.VSTO.CCForm.SaveExcelFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MapExtGenerAcitviDDLDataTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MapExtGenerAcitviDDLDataTable(string userNo, string sid, string pkValue, string mapExtMyPK, string cheaneKey, string paras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVstoExtensionVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVstoExtensionVersion();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pkValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public GenerExcelFileRequest() {
        }
        
        public GenerExcelFileRequest(string userNo, string sid, string frmID, string pkValue, byte[] bytes) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.pkValue = pkValue;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GenerExcelFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public GenerExcelFileResponse() {
        }
        
        public GenerExcelFileResponse(bool GenerExcelFileResult, byte[] bytes) {
            this.GenerExcelFileResult = GenerExcelFileResult;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pkValue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string mainTableAtParas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Data.DataSet dsDtlsChange;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public System.Data.DataSet dsDtlsOld;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] byt;
        
        public SaveExcelFileRequest() {
        }
        
        public SaveExcelFileRequest(string userNo, string sid, string frmID, string pkValue, string mainTableAtParas, System.Data.DataSet dsDtlsChange, System.Data.DataSet dsDtlsOld, byte[] byt) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.pkValue = pkValue;
            this.mainTableAtParas = mainTableAtParas;
            this.dsDtlsChange = dsDtlsChange;
            this.dsDtlsOld = dsDtlsOld;
            this.byt = byt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileResponse {
        
        public SaveExcelFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCFormAPISoapChannel : BP.VSTO.CCForm.CCFormAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCFormAPISoapClient : System.ServiceModel.ClientBase<BP.VSTO.CCForm.CCFormAPISoap>, BP.VSTO.CCForm.CCFormAPISoap {
        
        public CCFormAPISoapClient() {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.VSTO.CCForm.GenerExcelFileResponse BP.VSTO.CCForm.CCFormAPISoap.GenerExcelFile(BP.VSTO.CCForm.GenerExcelFileRequest request) {
            return base.Channel.GenerExcelFile(request);
        }
        
        public bool GenerExcelFile(string userNo, string sid, string frmID, string pkValue, ref byte[] bytes) {
            BP.VSTO.CCForm.GenerExcelFileRequest inValue = new BP.VSTO.CCForm.GenerExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.pkValue = pkValue;
            inValue.bytes = bytes;
            BP.VSTO.CCForm.GenerExcelFileResponse retVal = ((BP.VSTO.CCForm.CCFormAPISoap)(this)).GenerExcelFile(inValue);
            bytes = retVal.bytes;
            return retVal.GenerExcelFileResult;
        }
        
        public System.Data.DataSet GenerDBForVSTOExcelFrmModel(string userNo, string sid, string frmID, string pkValue, string atParas) {
            return base.Channel.GenerDBForVSTOExcelFrmModel(userNo, sid, frmID, pkValue, atParas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.VSTO.CCForm.SaveExcelFileResponse BP.VSTO.CCForm.CCFormAPISoap.SaveExcelFile(BP.VSTO.CCForm.SaveExcelFileRequest request) {
            return base.Channel.SaveExcelFile(request);
        }
        
        public void SaveExcelFile(string userNo, string sid, string frmID, string pkValue, string mainTableAtParas, System.Data.DataSet dsDtlsChange, System.Data.DataSet dsDtlsOld, byte[] byt) {
            BP.VSTO.CCForm.SaveExcelFileRequest inValue = new BP.VSTO.CCForm.SaveExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.pkValue = pkValue;
            inValue.mainTableAtParas = mainTableAtParas;
            inValue.dsDtlsChange = dsDtlsChange;
            inValue.dsDtlsOld = dsDtlsOld;
            inValue.byt = byt;
            BP.VSTO.CCForm.SaveExcelFileResponse retVal = ((BP.VSTO.CCForm.CCFormAPISoap)(this)).SaveExcelFile(inValue);
        }
        
        public System.Data.DataTable MapExtGenerAcitviDDLDataTable(string userNo, string sid, string pkValue, string mapExtMyPK, string cheaneKey, string paras) {
            return base.Channel.MapExtGenerAcitviDDLDataTable(userNo, sid, pkValue, mapExtMyPK, cheaneKey, paras);
        }
        
        public string GetVstoExtensionVersion() {
            return base.Channel.GetVstoExtensionVersion();
        }
    }
}
