//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFlowWord2007.DocFlow {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocFlow.DocFlowSoap")]
    public interface DocFlowSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSettingByKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSettingByKey(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoTypeDocFlow", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DoTypeDocFlow(string doType, object p1, object p2, object p3, object p4, object p5, object p6, object p7);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLReturnString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RunSQLReturnString(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerOID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GenerOID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CfgKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CfgKey(string kev);
        
        // CODEGEN: 参数“FileByte”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CCFlowWord2007.DocFlow.UploadFileResponse UploadFile(CCFlowWord2007.DocFlow.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RunSQL(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RunSQLs(string sqls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveEn(string vals);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLReturnTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable RunSQLReturnTable(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLReturnValInt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RunSQLReturnValInt(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLReturnValFloat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        float RunSQLReturnValFloat(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RunSQLReturnTableS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RunSQLReturnTableS(string sqls);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParseStringToPinyin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ParseStringToPinyin(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestSFTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RequestSFTable(string ensName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveEnum(string enumKey, string enumLab, string cfg);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileByte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(byte[] FileByte, string fileName) {
            this.FileByte = FileByte;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocFlowSoapChannel : CCFlowWord2007.DocFlow.DocFlowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocFlowSoapClient : System.ServiceModel.ClientBase<CCFlowWord2007.DocFlow.DocFlowSoap>, CCFlowWord2007.DocFlow.DocFlowSoap {
        
        public DocFlowSoapClient() {
        }
        
        public DocFlowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocFlowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocFlowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocFlowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSettingByKey(string key) {
            return base.Channel.GetSettingByKey(key);
        }
        
        public string DoTypeDocFlow(string doType, object p1, object p2, object p3, object p4, object p5, object p6, object p7) {
            return base.Channel.DoTypeDocFlow(doType, p1, p2, p3, p4, p5, p6, p7);
        }
        
        public string RunSQLReturnString(string sql) {
            return base.Channel.RunSQLReturnString(sql);
        }
        
        public int GenerOID() {
            return base.Channel.GenerOID();
        }
        
        public string CfgKey(string kev) {
            return base.Channel.CfgKey(kev);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CCFlowWord2007.DocFlow.UploadFileResponse CCFlowWord2007.DocFlow.DocFlowSoap.UploadFile(CCFlowWord2007.DocFlow.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] FileByte, string fileName) {
            CCFlowWord2007.DocFlow.UploadFileRequest inValue = new CCFlowWord2007.DocFlow.UploadFileRequest();
            inValue.FileByte = FileByte;
            inValue.fileName = fileName;
            CCFlowWord2007.DocFlow.UploadFileResponse retVal = ((CCFlowWord2007.DocFlow.DocFlowSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        public int RunSQL(string sql) {
            return base.Channel.RunSQL(sql);
        }
        
        public int RunSQLs(string sqls) {
            return base.Channel.RunSQLs(sqls);
        }
        
        public string SaveEn(string vals) {
            return base.Channel.SaveEn(vals);
        }
        
        public System.Data.DataTable RunSQLReturnTable(string sql) {
            return base.Channel.RunSQLReturnTable(sql);
        }
        
        public int RunSQLReturnValInt(string sql) {
            return base.Channel.RunSQLReturnValInt(sql);
        }
        
        public float RunSQLReturnValFloat(string sql) {
            return base.Channel.RunSQLReturnValFloat(sql);
        }
        
        public string RunSQLReturnTableS(string sqls) {
            return base.Channel.RunSQLReturnTableS(sqls);
        }
        
        public string ParseStringToPinyin(string name) {
            return base.Channel.ParseStringToPinyin(name);
        }
        
        public string RequestSFTable(string ensName) {
            return base.Channel.RequestSFTable(ensName);
        }
        
        public string SaveEnum(string enumKey, string enumLab, string cfg) {
            return base.Channel.SaveEnum(enumKey, enumLab, cfg);
        }
    }
}
