//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFlowExcel2007.CCForm {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCForm.CCFormAPISoap")]
    public interface CCFormAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        // CODEGEN: 参数“GenerExcelFileResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CCFlowExcel2007.CCForm.GenerExcelFileResponse GenerExcelFile(CCFlowExcel2007.CCForm.GenerExcelFileRequest request);
        
        // CODEGEN: 参数“byt”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CCFlowExcel2007.CCForm.SaveExcelFileResponse SaveExcelFile(CCFlowExcel2007.CCForm.SaveExcelFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int oid;
        
        public GenerExcelFileRequest() {
        }
        
        public GenerExcelFileRequest(string userNo, string sid, string frmID, int oid) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.oid = oid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GenerExcelFileResult;
        
        public GenerExcelFileResponse() {
        }
        
        public GenerExcelFileResponse(byte[] GenerExcelFileResult) {
            this.GenerExcelFileResult = GenerExcelFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int oid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string json;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] byt;
        
        public SaveExcelFileRequest() {
        }
        
        public SaveExcelFileRequest(string userNo, string sid, string frmID, int oid, string json, byte[] byt) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.oid = oid;
            this.json = json;
            this.byt = byt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveExcelFileResult;
        
        public SaveExcelFileResponse() {
        }
        
        public SaveExcelFileResponse(bool SaveExcelFileResult) {
            this.SaveExcelFileResult = SaveExcelFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCFormAPISoapChannel : CCFlowExcel2007.CCForm.CCFormAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCFormAPISoapClient : System.ServiceModel.ClientBase<CCFlowExcel2007.CCForm.CCFormAPISoap>, CCFlowExcel2007.CCForm.CCFormAPISoap {
        
        public CCFormAPISoapClient() {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CCFlowExcel2007.CCForm.GenerExcelFileResponse CCFlowExcel2007.CCForm.CCFormAPISoap.GenerExcelFile(CCFlowExcel2007.CCForm.GenerExcelFileRequest request) {
            return base.Channel.GenerExcelFile(request);
        }
        
        public byte[] GenerExcelFile(string userNo, string sid, string frmID, int oid) {
            CCFlowExcel2007.CCForm.GenerExcelFileRequest inValue = new CCFlowExcel2007.CCForm.GenerExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.oid = oid;
            CCFlowExcel2007.CCForm.GenerExcelFileResponse retVal = ((CCFlowExcel2007.CCForm.CCFormAPISoap)(this)).GenerExcelFile(inValue);
            return retVal.GenerExcelFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CCFlowExcel2007.CCForm.SaveExcelFileResponse CCFlowExcel2007.CCForm.CCFormAPISoap.SaveExcelFile(CCFlowExcel2007.CCForm.SaveExcelFileRequest request) {
            return base.Channel.SaveExcelFile(request);
        }
        
        public bool SaveExcelFile(string userNo, string sid, string frmID, int oid, string json, byte[] byt) {
            CCFlowExcel2007.CCForm.SaveExcelFileRequest inValue = new CCFlowExcel2007.CCForm.SaveExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.oid = oid;
            inValue.json = json;
            inValue.byt = byt;
            CCFlowExcel2007.CCForm.SaveExcelFileResponse retVal = ((CCFlowExcel2007.CCForm.CCFormAPISoap)(this)).SaveExcelFile(inValue);
            return retVal.SaveExcelFileResult;
        }
    }
}
