//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFormExcel2010.CCForm {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCForm.CCFormAPISoap")]
    public interface CCFormAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        // CODEGEN: 参数“bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CCFormExcel2010.CCForm.GenerExcelFileResponse GenerExcelFile(CCFormExcel2010.CCForm.GenerExcelFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerDBForVSTOExcelFrmModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GenerDBForVSTOExcelFrmModel(string userNo, string sid, string frmID, int oid);
        
        // CODEGEN: 参数“byt”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveExcelFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CCFormExcel2010.CCForm.SaveExcelFileResponse SaveExcelFile(CCFormExcel2010.CCForm.SaveExcelFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int oid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public GenerExcelFileRequest() {
        }
        
        public GenerExcelFileRequest(string userNo, string sid, string frmID, int oid, byte[] bytes) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.oid = oid;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GenerExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GenerExcelFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GenerExcelFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        public GenerExcelFileResponse() {
        }
        
        public GenerExcelFileResponse(bool GenerExcelFileResult, byte[] bytes) {
            this.GenerExcelFileResult = GenerExcelFileResult;
            this.bytes = bytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string frmID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int oid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string mainTableAtParas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public System.Data.DataSet dsDtls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] byt;
        
        public SaveExcelFileRequest() {
        }
        
        public SaveExcelFileRequest(string userNo, string sid, string frmID, int oid, string mainTableAtParas, System.Data.DataSet dsDtls, byte[] byt) {
            this.userNo = userNo;
            this.sid = sid;
            this.frmID = frmID;
            this.oid = oid;
            this.mainTableAtParas = mainTableAtParas;
            this.dsDtls = dsDtls;
            this.byt = byt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExcelFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveExcelFileResponse {
        
        public SaveExcelFileResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CCFormAPISoapChannel : CCFormExcel2010.CCForm.CCFormAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCFormAPISoapClient : System.ServiceModel.ClientBase<CCFormExcel2010.CCForm.CCFormAPISoap>, CCFormExcel2010.CCForm.CCFormAPISoap {
        
        public CCFormAPISoapClient() {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCFormAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CCFormExcel2010.CCForm.GenerExcelFileResponse CCFormExcel2010.CCForm.CCFormAPISoap.GenerExcelFile(CCFormExcel2010.CCForm.GenerExcelFileRequest request) {
            return base.Channel.GenerExcelFile(request);
        }
        
        public bool GenerExcelFile(string userNo, string sid, string frmID, int oid, ref byte[] bytes) {
            CCFormExcel2010.CCForm.GenerExcelFileRequest inValue = new CCFormExcel2010.CCForm.GenerExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.oid = oid;
            inValue.bytes = bytes;
            CCFormExcel2010.CCForm.GenerExcelFileResponse retVal = ((CCFormExcel2010.CCForm.CCFormAPISoap)(this)).GenerExcelFile(inValue);
            bytes = retVal.bytes;
            return retVal.GenerExcelFileResult;
        }
        
        public System.Data.DataSet GenerDBForVSTOExcelFrmModel(string userNo, string sid, string frmID, int oid) {
            return base.Channel.GenerDBForVSTOExcelFrmModel(userNo, sid, frmID, oid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CCFormExcel2010.CCForm.SaveExcelFileResponse CCFormExcel2010.CCForm.CCFormAPISoap.SaveExcelFile(CCFormExcel2010.CCForm.SaveExcelFileRequest request) {
            return base.Channel.SaveExcelFile(request);
        }
        
        public void SaveExcelFile(string userNo, string sid, string frmID, int oid, string mainTableAtParas, System.Data.DataSet dsDtls, byte[] byt) {
            CCFormExcel2010.CCForm.SaveExcelFileRequest inValue = new CCFormExcel2010.CCForm.SaveExcelFileRequest();
            inValue.userNo = userNo;
            inValue.sid = sid;
            inValue.frmID = frmID;
            inValue.oid = oid;
            inValue.mainTableAtParas = mainTableAtParas;
            inValue.dsDtls = dsDtls;
            inValue.byt = byt;
            CCFormExcel2010.CCForm.SaveExcelFileResponse retVal = ((CCFormExcel2010.CCForm.CCFormAPISoap)(this)).SaveExcelFile(inValue);
        }
    }
}
