//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrialAutomationWorkflow.ccbpmAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ccbpmAPI.IndustrialAutomationWorkflowWSAPISoap")]
    public interface IndustrialAutomationWorkflowWSAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Node_CreateBlankWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        long Node_CreateBlankWork(string userNo, string sid, string flowNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Node_SendWork", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Node_SendWork(string userNo, string sid, string flowNo, int nodeID, long workid, int toNodeID, string toEmps, string paras);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Port_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Port_Login(string userNo, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndustrialAutomationWorkflowWSAPISoapChannel : IndustrialAutomationWorkflow.ccbpmAPI.IndustrialAutomationWorkflowWSAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndustrialAutomationWorkflowWSAPISoapClient : System.ServiceModel.ClientBase<IndustrialAutomationWorkflow.ccbpmAPI.IndustrialAutomationWorkflowWSAPISoap>, IndustrialAutomationWorkflow.ccbpmAPI.IndustrialAutomationWorkflowWSAPISoap {
        
        public IndustrialAutomationWorkflowWSAPISoapClient() {
        }
        
        public IndustrialAutomationWorkflowWSAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndustrialAutomationWorkflowWSAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndustrialAutomationWorkflowWSAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndustrialAutomationWorkflowWSAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public long Node_CreateBlankWork(string userNo, string sid, string flowNo) {
            return base.Channel.Node_CreateBlankWork(userNo, sid, flowNo);
        }
        
        public string Node_SendWork(string userNo, string sid, string flowNo, int nodeID, long workid, int toNodeID, string toEmps, string paras) {
            return base.Channel.Node_SendWork(userNo, sid, flowNo, nodeID, workid, toNodeID, toEmps, paras);
        }
        
        public string Port_Login(string userNo, string pass) {
            return base.Channel.Port_Login(userNo, pass);
        }
    }
}
