//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.AAA {

    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BP.AAA.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Direction 的本地化字符串。
        /// </summary>
        public static string Button_AddDirection {
            get {
                return ResourceManager.GetString("Button_AddDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add FlowNode 的本地化字符串。
        /// </summary>
        public static string Button_AddFlowNode {
            get {
                return ResourceManager.GetString("Button_AddFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Label 的本地化字符串。
        /// </summary>
        public static string Button_AddLabel {
            get {
                return ResourceManager.GetString("Button_AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddTemplate 的本地化字符串。
        /// </summary>
        public static string Button_AddTemplate {
            get {
                return ResourceManager.GetString("Button_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Button_Apply {
            get {
                return ResourceManager.GetString("Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancle 的本地化字符串。
        /// </summary>
        public static string Button_Cancle {
            get {
                return ResourceManager.GetString("Button_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Button_ClearContainer {
            get {
                return ResourceManager.GetString("Button_ClearContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatePicture 的本地化字符串。
        /// </summary>
        public static string Button_CreatePicture {
            get {
                return ResourceManager.GetString("Button_CreatePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreatTemplate 的本地化字符串。
        /// </summary>
        public static string Button_CreatTemplate {
            get {
                return ResourceManager.GetString("Button_CreatTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Button_DelFlow {
            get {
                return ResourceManager.GetString("Button_DelFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DesignerTable 的本地化字符串。
        /// </summary>
        public static string Button_DesignerTable {
            get {
                return ResourceManager.GetString("Button_DesignerTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Button_ExportToXml {
            get {
                return ResourceManager.GetString("Button_ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowCheck 的本地化字符串。
        /// </summary>
        public static string Button_FlowCheck {
            get {
                return ResourceManager.GetString("Button_FlowCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowProper 的本地化字符串。
        /// </summary>
        public static string Button_FlowProper {
            get {
                return ResourceManager.GetString("Button_FlowProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlowRptDefinition 的本地化字符串。
        /// </summary>
        public static string Button_FlowRptDefinition {
            get {
                return ResourceManager.GetString("Button_FlowRptDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Button_ImportFromXml {
            get {
                return ResourceManager.GetString("Button_ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewFlow 的本地化字符串。
        /// </summary>
        public static string Button_NewFlow {
            get {
                return ResourceManager.GetString("Button_NewFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Button_Previous {
            get {
                return ResourceManager.GetString("Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunFlow 的本地化字符串。
        /// </summary>
        public static string Button_RunFlow {
            get {
                return ResourceManager.GetString("Button_RunFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowLine 的本地化字符串。
        /// </summary>
        public static string Button_ShowLine {
            get {
                return ResourceManager.GetString("Button_ShowLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string Button_Zoom {
            get {
                return ResourceManager.GetString("Button_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 will delete Object,continue? 的本地化字符串。
        /// </summary>
        public static string Comfirm_Delete {
            get {
                return ResourceManager.GetString("Comfirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string ContainerHeight {
            get {
                return ResourceManager.GetString("ContainerHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string ContainerWidth {
            get {
                return ResourceManager.GetString("ContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 will delete WorkFlow,continue? 的本地化字符串。
        /// </summary>
        public static string DeleteFlow {
            get {
                return ResourceManager.GetString("DeleteFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 will delete WorkFlow Sort,continue? 的本地化字符串。
        /// </summary>
        public static string DeleteFlowSort {
            get {
                return ResourceManager.GetString("DeleteFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditon 的本地化字符串。
        /// </summary>
        public static string DirectionCondition {
            get {
                return ResourceManager.GetString("DirectionCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        public static string DirectionLineType_Line {
            get {
                return ResourceManager.GetString("DirectionLineType_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polyline 的本地化字符串。
        /// </summary>
        public static string DirectionLineType_Polyline {
            get {
                return ResourceManager.GetString("DirectionLineType_Polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string DirectionName {
            get {
                return ResourceManager.GetString("DirectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string FlowNodeName {
            get {
                return ResourceManager.GetString("FlowNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string FlowNodeType {
            get {
                return ResourceManager.GetString("FlowNodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AND_BRANCH 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_AND_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AND_MERGE 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_AND_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_AND_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AUTOMATION 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_AUTOMATION {
            get {
                return ResourceManager.GetString("FlowNodeType_AUTOMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COMPLETION 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_COMPLETION {
            get {
                return ResourceManager.GetString("FlowNodeType_COMPLETION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DUMMY 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_DUMMY {
            get {
                return ResourceManager.GetString("FlowNodeType_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INITIAL 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_INITIAL {
            get {
                return ResourceManager.GetString("FlowNodeType_INITIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INTERACTION 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_INTERACTION {
            get {
                return ResourceManager.GetString("FlowNodeType_INTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR_BRANCH 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_OR_BRANCH {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR_MERGE 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_OR_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_OR_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SUBPROCESS 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_SUBPROCESS {
            get {
                return ResourceManager.GetString("FlowNodeType_SUBPROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VOTE_MERGE 的本地化字符串。
        /// </summary>
        public static string FlowNodeType_VOTE_MERGE {
            get {
                return ResourceManager.GetString("FlowNodeType_VOTE_MERGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Save ? 的本地化字符串。
        /// </summary>
        public static string IsSave {
            get {
                return ResourceManager.GetString("IsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignBottom 的本地化字符串。
        /// </summary>
        public static string Menu_AlignBottom {
            get {
                return ResourceManager.GetString("Menu_AlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignLeft 的本地化字符串。
        /// </summary>
        public static string Menu_AlignLeft {
            get {
                return ResourceManager.GetString("Menu_AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignRight 的本地化字符串。
        /// </summary>
        public static string Menu_AlignRight {
            get {
                return ResourceManager.GetString("Menu_AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AlignTop 的本地化字符串。
        /// </summary>
        public static string Menu_AlignTop {
            get {
                return ResourceManager.GetString("Menu_AlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyDirection {
            get {
                return ResourceManager.GetString("Menu_CopyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyFlowNode {
            get {
                return ResourceManager.GetString("Menu_CopyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopyLabel {
            get {
                return ResourceManager.GetString("Menu_CopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Menu_CopySelected {
            get {
                return ResourceManager.GetString("Menu_CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteDirection {
            get {
                return ResourceManager.GetString("Menu_DeleteDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteFlowNode {
            get {
                return ResourceManager.GetString("Menu_DeleteFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteLabel {
            get {
                return ResourceManager.GetString("Menu_DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteSelected {
            get {
                return ResourceManager.GetString("Menu_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Menu_ModifyDirection {
            get {
                return ResourceManager.GetString("Menu_ModifyDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Menu_ModifyFlowNode {
            get {
                return ResourceManager.GetString("Menu_ModifyFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowGridLines 的本地化字符串。
        /// </summary>
        public static string Menu_ShowGridLines {
            get {
                return ResourceManager.GetString("Menu_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin-activitity can not have pre-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_BeginActivitiesCanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_BeginActivitiesCanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 begin and end FlowNode  can not be the same. 的本地化字符串。
        /// </summary>
        public static string Message_BeginAndEndFlowNodeCanNotBeTheSame {
            get {
                return ResourceManager.GetString("Message_BeginAndEndFlowNodeCanNotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not have pre-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_CanNotHavePreFlowNode {
            get {
                return ResourceManager.GetString("Message_CanNotHavePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 end-activitity can not have follow-up activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_EndFlowNodeCanNotHaveFollowUpActivitiy {
            get {
                return ResourceManager.GetString("Message_EndFlowNodeCanNotHaveFollowUpActivitiy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 branch-FlowNode only have one pre-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_HeLiuNodeOnlyHaveOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_HeLiuNodeOnlyHaveOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please modify workflow  in accordance with tips. 的本地化字符串。
        /// </summary>
        public static string Message_ModifyWorkFlowByTip {
            get {
                return ResourceManager.GetString("Message_ModifyWorkFlowByTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to begin-activitiy and end-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToBeginAndEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginAndEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to begin-activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 rule must be linked to end-activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_MustBeLinkToEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustBeLinkToEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one end-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOneEndFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneEndFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one follow-up FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have at least one pre-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveAtLeastOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveAtLeastOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one begin-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOneBeginFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneBeginFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one follow-up FlowNode 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOneFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOneFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 must have only one pre-FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_MustHaveOnlyOnePreFlowNode {
            get {
                return ResourceManager.GetString("Message_MustHaveOnlyOnePreFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not have follow-up FlowNode. 的本地化字符串。
        /// </summary>
        public static string Message_NotHaveFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_NotHaveFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 require the installation of pre-and follow-up activities. 的本地化字符串。
        /// </summary>
        public static string Message_RequireTheInstallationOfPreAndFollowupFlowNode {
            get {
                return ResourceManager.GetString("Message_RequireTheInstallationOfPreAndFollowupFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WorkFlow had saved! 的本地化字符串。
        /// </summary>
        public static string Message_Saved {
            get {
                return ResourceManager.GetString("Message_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 merge-activitity  only have one follow-up activitiy. 的本地化字符串。
        /// </summary>
        public static string Message_SubThreadNodeOnlyHaveAFollowUpFlowNode {
            get {
                return ResourceManager.GetString("Message_SubThreadNodeOnlyHaveAFollowUpFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The same rule that already exists. 的本地化字符串。
        /// </summary>
        public static string Message_TheSameDirectionThatAlreadyExist {
            get {
                return ResourceManager.GetString("Message_TheSameDirectionThatAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewDirection 的本地化字符串。
        /// </summary>
        public static string NewDirection {
            get {
                return ResourceManager.GetString("NewDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewFlowNode 的本地化字符串。
        /// </summary>
        public static string NewFlowNode {
            get {
                return ResourceManager.GetString("NewFlowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewFowSort 的本地化字符串。
        /// </summary>
        public static string NewFlowSort {
            get {
                return ResourceManager.GetString("NewFlowSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewLabel 的本地化字符串。
        /// </summary>
        public static string NewLable {
            get {
                return ResourceManager.GetString("NewLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlow 的本地化字符串。
        /// </summary>
        public static string OpenFlow {
            get {
                return ResourceManager.GetString("OpenFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direction 的本地化字符串。
        /// </summary>
        public static string RepeatDirection {
            get {
                return ResourceManager.GetString("RepeatDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal 的本地化字符串。
        /// </summary>
        public static string RepeatDirection_Horizontal {
            get {
                return ResourceManager.GetString("RepeatDirection_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical 的本地化字符串。
        /// </summary>
        public static string RepeatDirection_Vertical {
            get {
                return ResourceManager.GetString("RepeatDirection_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubFlow 的本地化字符串。
        /// </summary>
        public static string SubFlow {
            get {
                return ResourceManager.GetString("SubFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dept 的本地化字符串。
        /// </summary>
        public static string TbDept {
            get {
                return ResourceManager.GetString("TbDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flow 的本地化字符串。
        /// </summary>
        public static string TbItemFlow {
            get {
                return ResourceManager.GetString("TbItemFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Station 的本地化字符串。
        /// </summary>
        public static string TbStation {
            get {
                return ResourceManager.GetString("TbStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string UpdateLable {
            get {
                return ResourceManager.GetString("UpdateLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
    }
}
