//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCFlow.CloundWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloundWS.WSSoap")]
    public interface WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFlowDir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDataByNo(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSonDirByParentNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSonDirByParentNo(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTempByDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFlowTempByDir(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyFlowTemp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRecentlyFlowTemp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetTotalCount(string searchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPagingData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPagingData(string searchText, int pageIdx, int pageSize, bool isPost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTemplateByGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFlowTemplateByGuid(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFlowXML(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowsTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFlowsTree();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : CCFlow.CloundWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<CCFlow.CloundWS.WSSoap>, CCFlow.CloundWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetFlowDir() {
            return base.Channel.GetFlowDir();
        }
        
        public System.Data.DataTable GetDataByNo(string no) {
            return base.Channel.GetDataByNo(no);
        }
        
        public System.Data.DataTable GetSonDirByParentNo(string no) {
            return base.Channel.GetSonDirByParentNo(no);
        }
        
        public System.Data.DataTable GetFlowTempByDir(string no) {
            return base.Channel.GetFlowTempByDir(no);
        }
        
        public System.Data.DataTable GetRecentlyFlowTemp() {
            return base.Channel.GetRecentlyFlowTemp();
        }
        
        public int GetTotalCount(string searchText) {
            return base.Channel.GetTotalCount(searchText);
        }
        
        public System.Data.DataTable GetPagingData(string searchText, int pageIdx, int pageSize, bool isPost) {
            return base.Channel.GetPagingData(searchText, pageIdx, pageSize, isPost);
        }
        
        public System.Data.DataTable GetFlowTemplateByGuid(string guid) {
            return base.Channel.GetFlowTemplateByGuid(guid);
        }
        
        public string GetFlowXML(string guid) {
            return base.Channel.GetFlowXML(guid);
        }
        
        public string GetFlowsTree() {
            return base.Channel.GetFlowsTree();
        }
    }
}
