//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BP.WF.CloudWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CloudWS.WSSoap")]
    public interface WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNetState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetNetState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPriFormDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddPriFormDir(string userNo, string pwd, string guid, string parentNo, string dirName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePriFormDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeletePriFormDir(string userNo, string pwd, string guid, string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditPriFormDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EditPriFormDir(string userNo, string pwd, string guid, string no, string dirName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormPagingData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFormPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormTotalCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetFormTotalCount(bool isPublic, string searchText, string dirStr, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriFormDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PriFormDir(string userNo, string pwd, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyPriFormTemp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRecentlyPriFormTemp(string userNo, string pwd, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePubFormToPri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SavePubFormToPri(string userNo, string pwd, string guid, string dir, string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPubFormTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPubFormTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyFormTemp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRecentlyFormTemp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFormData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] GetFormData(bool isPublic, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePubToPri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string SavePubToPri(string userNo, string pwd, string guid, string dir, string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PriLogin(string userNo, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsExitUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string IsExitUser(string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriRegUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        string PriRegUser(string userNo, string userName, string password, string email, string tel, string qq, int userType, int userTarget);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PriFlowDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable PriFlowDir(string userNo, string pwd, string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPriFlowDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool AddPriFlowDir(string userNo, string pwd, string guid, string parentNo, string dirName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePriFlowDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool DeletePriFlowDir(string userNo, string pwd, string guid, string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditPriFlowDir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool EditPriFlowDir(string userNo, string pwd, string guid, string no, string dirName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyPriFlowTemp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetRecentlyPriFlowTemp(string userNo, string pwd, string guid);
        
        // CODEGEN: 参数“bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePriFlowTemplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BP.WF.CloudWS.SavePriFlowTempleteResponse SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPriFlowTemplateByGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetPriFlowTemplateByGuid(string guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPubFlowTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetPubFlowTree();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataByNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetDataByNo(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSonDirByParentNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetSonDirByParentNo(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRecentlyFlowTemp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetRecentlyFlowTemp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int GetTotalCount(bool isPublic, string searchText, string dirStr, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPagingData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTemplateByGuid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetFlowTemplateByGuid(string guid);
        
        // CODEGEN: 参数“GetFlowXMLResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BP.WF.CloudWS.GetFlowXMLResponse GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCloudFlowsDDlTreeDt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetCloudFlowsDDlTreeDt();
        
        // CODEGEN: 参数“bytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveToFlowTemplete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BP.WF.CloudWS.SaveToFlowTempleteResponse SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlowTemFromCloud", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Data.DataTable GetFlowTemFromCloud(string str);
        
        // CODEGEN: 参数“GetImageBytesByNoResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetImageBytesByNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        BP.WF.CloudWS.GetImageBytesByNoResponse GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePriFlowTemplete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePriFlowTempleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string dir;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string flowName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string userNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string nodeNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int nodesCount;
        
        public SavePriFlowTempleteRequest() {
        }
        
        public SavePriFlowTempleteRequest(string dir, string flowName, byte[] bytes, string userNo, string nodeNames, int nodesCount) {
            this.dir = dir;
            this.flowName = flowName;
            this.bytes = bytes;
            this.userNo = userNo;
            this.nodeNames = nodeNames;
            this.nodesCount = nodesCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SavePriFlowTempleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SavePriFlowTempleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SavePriFlowTempleteResult;
        
        public SavePriFlowTempleteResponse() {
        }
        
        public SavePriFlowTempleteResponse(bool SavePriFlowTempleteResult) {
            this.SavePriFlowTempleteResult = SavePriFlowTempleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFlowXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFlowXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool isPublic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string guid;
        
        public GetFlowXMLRequest() {
        }
        
        public GetFlowXMLRequest(bool isPublic, string guid) {
            this.isPublic = isPublic;
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFlowXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFlowXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFlowXMLResult;
        
        public GetFlowXMLResponse() {
        }
        
        public GetFlowXMLResponse(byte[] GetFlowXMLResult) {
            this.GetFlowXMLResult = GetFlowXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveToFlowTemplete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveToFlowTempleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string flowName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] bytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sharer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string nodeNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int nodesCount;
        
        public SaveToFlowTempleteRequest() {
        }
        
        public SaveToFlowTempleteRequest(string no, string flowName, byte[] bytes, string sharer, string nodeNames, int nodesCount) {
            this.no = no;
            this.flowName = flowName;
            this.bytes = bytes;
            this.sharer = sharer;
            this.nodeNames = nodeNames;
            this.nodesCount = nodesCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveToFlowTempleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveToFlowTempleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveToFlowTempleteResult;
        
        public SaveToFlowTempleteResponse() {
        }
        
        public SaveToFlowTempleteResponse(bool SaveToFlowTempleteResult) {
            this.SaveToFlowTempleteResult = SaveToFlowTempleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetImageBytesByNo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetImageBytesByNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string no;
        
        public GetImageBytesByNoRequest() {
        }
        
        public GetImageBytesByNoRequest(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetImageBytesByNoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetImageBytesByNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetImageBytesByNoResult;
        
        public GetImageBytesByNoResponse() {
        }
        
        public GetImageBytesByNoResponse(byte[] GetImageBytesByNoResult) {
            this.GetImageBytesByNoResult = GetImageBytesByNoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : BP.WF.CloudWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<BP.WF.CloudWS.WSSoap>, BP.WF.CloudWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetNetState() {
            return base.Channel.GetNetState();
        }
        
        public bool AddPriFormDir(string userNo, string pwd, string guid, string parentNo, string dirName) {
            return base.Channel.AddPriFormDir(userNo, pwd, guid, parentNo, dirName);
        }
        
        public bool DeletePriFormDir(string userNo, string pwd, string guid, string no) {
            return base.Channel.DeletePriFormDir(userNo, pwd, guid, no);
        }
        
        public bool EditPriFormDir(string userNo, string pwd, string guid, string no, string dirName) {
            return base.Channel.EditPriFormDir(userNo, pwd, guid, no, dirName);
        }
        
        public System.Data.DataTable GetFormPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo) {
            return base.Channel.GetFormPagingData(isPublic, searchText, pageIdx, pageSize, dirStr, userNo);
        }
        
        public int GetFormTotalCount(bool isPublic, string searchText, string dirStr, string userNo) {
            return base.Channel.GetFormTotalCount(isPublic, searchText, dirStr, userNo);
        }
        
        public System.Data.DataTable PriFormDir(string userNo, string pwd, string guid) {
            return base.Channel.PriFormDir(userNo, pwd, guid);
        }
        
        public System.Data.DataTable GetRecentlyPriFormTemp(string userNo, string pwd, string guid) {
            return base.Channel.GetRecentlyPriFormTemp(userNo, pwd, guid);
        }
        
        public string SavePubFormToPri(string userNo, string pwd, string guid, string dir, string no) {
            return base.Channel.SavePubFormToPri(userNo, pwd, guid, dir, no);
        }
        
        public System.Data.DataTable GetPubFormTree() {
            return base.Channel.GetPubFormTree();
        }
        
        public System.Data.DataTable GetRecentlyFormTemp() {
            return base.Channel.GetRecentlyFormTemp();
        }
        
        public object[] GetFormData(bool isPublic, string guid) {
            return base.Channel.GetFormData(isPublic, guid);
        }
        
        public string SavePubToPri(string userNo, string pwd, string guid, string dir, string no) {
            return base.Channel.SavePubToPri(userNo, pwd, guid, dir, no);
        }
        
        public string PriLogin(string userNo, string password) {
            return base.Channel.PriLogin(userNo, password);
        }
        
        public string IsExitUser(string userNo) {
            return base.Channel.IsExitUser(userNo);
        }
        
        public string PriRegUser(string userNo, string userName, string password, string email, string tel, string qq, int userType, int userTarget) {
            return base.Channel.PriRegUser(userNo, userName, password, email, tel, qq, userType, userTarget);
        }
        
        public System.Data.DataTable PriFlowDir(string userNo, string pwd, string guid) {
            return base.Channel.PriFlowDir(userNo, pwd, guid);
        }
        
        public bool AddPriFlowDir(string userNo, string pwd, string guid, string parentNo, string dirName) {
            return base.Channel.AddPriFlowDir(userNo, pwd, guid, parentNo, dirName);
        }
        
        public bool DeletePriFlowDir(string userNo, string pwd, string guid, string no) {
            return base.Channel.DeletePriFlowDir(userNo, pwd, guid, no);
        }
        
        public bool EditPriFlowDir(string userNo, string pwd, string guid, string no, string dirName) {
            return base.Channel.EditPriFlowDir(userNo, pwd, guid, no, dirName);
        }
        
        public System.Data.DataTable GetRecentlyPriFlowTemp(string userNo, string pwd, string guid) {
            return base.Channel.GetRecentlyPriFlowTemp(userNo, pwd, guid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.WF.CloudWS.SavePriFlowTempleteResponse BP.WF.CloudWS.WSSoap.SavePriFlowTemplete(BP.WF.CloudWS.SavePriFlowTempleteRequest request) {
            return base.Channel.SavePriFlowTemplete(request);
        }
        
        public bool SavePriFlowTemplete(string dir, string flowName, byte[] bytes, string userNo, string nodeNames, int nodesCount) {
            BP.WF.CloudWS.SavePriFlowTempleteRequest inValue = new BP.WF.CloudWS.SavePriFlowTempleteRequest();
            inValue.dir = dir;
            inValue.flowName = flowName;
            inValue.bytes = bytes;
            inValue.userNo = userNo;
            inValue.nodeNames = nodeNames;
            inValue.nodesCount = nodesCount;
            BP.WF.CloudWS.SavePriFlowTempleteResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).SavePriFlowTemplete(inValue);
            return retVal.SavePriFlowTempleteResult;
        }
        
        public System.Data.DataTable GetPriFlowTemplateByGuid(string guid) {
            return base.Channel.GetPriFlowTemplateByGuid(guid);
        }
        
        public System.Data.DataTable GetPubFlowTree() {
            return base.Channel.GetPubFlowTree();
        }
        
        public System.Data.DataTable GetDataByNo(string no) {
            return base.Channel.GetDataByNo(no);
        }
        
        public System.Data.DataTable GetSonDirByParentNo(string no) {
            return base.Channel.GetSonDirByParentNo(no);
        }
        
        public System.Data.DataTable GetRecentlyFlowTemp() {
            return base.Channel.GetRecentlyFlowTemp();
        }
        
        public int GetTotalCount(bool isPublic, string searchText, string dirStr, string userNo) {
            return base.Channel.GetTotalCount(isPublic, searchText, dirStr, userNo);
        }
        
        public System.Data.DataTable GetPagingData(bool isPublic, string searchText, int pageIdx, int pageSize, string dirStr, string userNo) {
            return base.Channel.GetPagingData(isPublic, searchText, pageIdx, pageSize, dirStr, userNo);
        }
        
        public System.Data.DataTable GetFlowTemplateByGuid(string guid) {
            return base.Channel.GetFlowTemplateByGuid(guid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.WF.CloudWS.GetFlowXMLResponse BP.WF.CloudWS.WSSoap.GetFlowXML(BP.WF.CloudWS.GetFlowXMLRequest request) {
            return base.Channel.GetFlowXML(request);
        }
        
        public byte[] GetFlowXML(bool isPublic, string guid) {
            BP.WF.CloudWS.GetFlowXMLRequest inValue = new BP.WF.CloudWS.GetFlowXMLRequest();
            inValue.isPublic = isPublic;
            inValue.guid = guid;
            BP.WF.CloudWS.GetFlowXMLResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).GetFlowXML(inValue);
            return retVal.GetFlowXMLResult;
        }
        
        public System.Data.DataTable GetCloudFlowsDDlTreeDt() {
            return base.Channel.GetCloudFlowsDDlTreeDt();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.WF.CloudWS.SaveToFlowTempleteResponse BP.WF.CloudWS.WSSoap.SaveToFlowTemplete(BP.WF.CloudWS.SaveToFlowTempleteRequest request) {
            return base.Channel.SaveToFlowTemplete(request);
        }
        
        public bool SaveToFlowTemplete(string no, string flowName, byte[] bytes, string sharer, string nodeNames, int nodesCount) {
            BP.WF.CloudWS.SaveToFlowTempleteRequest inValue = new BP.WF.CloudWS.SaveToFlowTempleteRequest();
            inValue.no = no;
            inValue.flowName = flowName;
            inValue.bytes = bytes;
            inValue.sharer = sharer;
            inValue.nodeNames = nodeNames;
            inValue.nodesCount = nodesCount;
            BP.WF.CloudWS.SaveToFlowTempleteResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).SaveToFlowTemplete(inValue);
            return retVal.SaveToFlowTempleteResult;
        }
        
        public System.Data.DataTable GetFlowTemFromCloud(string str) {
            return base.Channel.GetFlowTemFromCloud(str);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BP.WF.CloudWS.GetImageBytesByNoResponse BP.WF.CloudWS.WSSoap.GetImageBytesByNo(BP.WF.CloudWS.GetImageBytesByNoRequest request) {
            return base.Channel.GetImageBytesByNo(request);
        }
        
        public byte[] GetImageBytesByNo(string no) {
            BP.WF.CloudWS.GetImageBytesByNoRequest inValue = new BP.WF.CloudWS.GetImageBytesByNoRequest();
            inValue.no = no;
            BP.WF.CloudWS.GetImageBytesByNoResponse retVal = ((BP.WF.CloudWS.WSSoap)(this)).GetImageBytesByNo(inValue);
            return retVal.GetImageBytesByNoResult;
        }
    }
}
